import { Over, Player } from "./interfaces/Interface";

export const teamA:  Player[] = [

    {
        id: 1,
        name: 'Rohit Sharma',
        role: 'Batsman',
        isOnStrike: true,
        isOut: false,
        run: 0,
        team: 'India',
        isCaptain: true,
        wicket: 0,
        ball: 0,
        isBatting: true,
        isBowling: false,
        over: 0,
    },
    {
        id: 2,
        name: 'Virat Kohli',
        role: 'Batsman',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'India',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: true,
        isBowling: false,
        over: 0,
    },
    {
        id: 3,
        name: 'Shubman Gill',
        role: 'Batsman',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'India',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 4,
        name: 'Suryakumar Yadav',
        role: 'Batsman',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'India',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 5,
        name: 'Shreyas Iyer',
        role: 'Batsman',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'India',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 6,
        name: 'Ravindra Jadeja',
        role: 'All rounder',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'India',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 7,
        name: 'Hardik Pandya',
        role: 'All rounder',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'India',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 8,
        name: 'Ravichandran Ashwin',
        role: 'All rounder',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'India',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 9,
        name: 'Mohammed Shami',
        role: 'Bowler',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'India',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 10,
        name: 'Kuldeep Yadav',
        role: 'Bowler',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'India',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 11,
        name: 'Jasprit Bumrah',
        role: 'Bowler',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'India',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: true,
        over: 0,
    },
];


export const teamB: Player[] = [
    {
        id: 12,
        name: 'Mitchell Marsh',
        role: 'Batsman',
        isOnStrike: true,
        isOut: false,
        run: 0,
        team: 'Australia',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: true,
        isBowling: false,
        over: 0,
    },
    {
        id: 13,
        name: 'David Warner',
        role: 'Batsman',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'Australia',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: true,
        isBowling: false,
        over: 0,
    },
    {
        id: 14,
        name: 'Travis Head',
        role: 'Batsman',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'Australia',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 15,
        name: 'Steven Smith',
        role: 'Batsman',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'Australia',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 16,
        name: 'Alex Carey',
        role: 'Batsman',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'Australia',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 17,
        name: 'Glenn Maxwell',
        role: 'All rounder',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'Australia',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 18,
        name: 'Pat Cummins',
        role: 'All rounder',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'Australia',
        isCaptain: true,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 19,
        name: 'Tim David',
        role: 'All rounder',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'Australia',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 20,
        name: 'Josh Hazlewood',
        role: 'Bowler',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'Australia',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 21,
        name: 'Cameron Green',
        role: 'Bowler',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'Australia',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: false,
        over: 0,
    },
    {
        id: 22,
        name: 'Mitchell Starc',
        role: 'Bowler',
        isOnStrike: false,
        isOut: false,
        run: 0,
        team: 'Australia',
        isCaptain: false,
        wicket: 0,
        ball: 0,
        isBatting: false,
        isBowling: true,
        over: 0,
    }
];


export const overTeamA: Over = {
    over1:[],
    over2:[],
    over3:[],
    over4:[],
    over5:[],
    over6:[]
}

export const overTeamB: Over = {
    over1:[],
    over2:[],
    over3:[],
    over4:[],
    over5:[],
    over6:[]
}





// export const newTeamData = [
//     {
//         id: 1,
//         name: 'Rohit Sharma',
//         role: 'Batsman',
//         isOnStrike: true,
//         isOut: false,
//         run: 0,
//         team: 'India',
//         isCaptain: true,
//         wicket: 0,
//         ball: 0,
//         isBatting: true
//     },
//     {
//         id: 2,
//         name: 'Virat Kohli',
//         role: 'Batsman',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'India',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: true
//     },
//     {
//         id: 3,
//         name: 'Shubman Gill',
//         role: 'Batsman',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'India',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 4,
//         name: 'Suryakumar Yadav',
//         role: 'Batsman',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'India',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 5,
//         name: 'Shreyas Iyer',
//         role: 'Batsman',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'India',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 6,
//         name: 'Ravindra Jadeja',
//         role: 'All rounder',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'India',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 7,
//         name: 'Hardik Pandya',
//         role: 'All rounder',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'India',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 8,
//         name: 'Ravichandran Ashwin',
//         role: 'All rounder',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'India',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 9,
//         name: 'Mohammed Shami',
//         role: 'Bowler',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'India',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 10,
//         name: 'Kuldeep Yadav',
//         role: 'Bowler',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'India',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 11,
//         name: 'Jasprit Bumrah',
//         role: 'Bowler',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'India',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },

//     // Team B
//     // Team B
//     // Team B
//     {
//         id: 12,
//         name: 'Mitchell Marsh',
//         role: 'Batsman',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'Australia',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 13,
//         name: 'David Warner',
//         role: 'Batsman',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'Australia',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 14,
//         name: 'Travis Head',
//         role: 'Batsman',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'Australia',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 15,
//         name: 'Steven Smith',
//         role: 'Batsman',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'Australia',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 16,
//         role: 'Batsman',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'Australia',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 17,
//         name: 'Glenn Maxwell',
//         role: 'All rounder',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'Australia',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 18,
//         name: 'Pat Cummins',
//         role: 'All rounder',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'Australia',
//         isCaptain: true,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 19,
//         name: 'Tim David',
//         role: 'All rounder',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'Australia',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 20,
//         name: 'Josh Hazlewood',
//         role: 'Bowler',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'Australia',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 21,
//         name: 'Cameron Green',
//         role: 'Bowler',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'Australia',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     },
//     {
//         id: 22,
//         name: 'Mitchell Starc',
//         role: 'Bowler',
//         isOnStrike: false,
//         isOut: false,
//         run: 0,
//         team: 'Australia',
//         isCaptain: false,
//         wicket: 0,
//         ball: 0,
//         isBatting: false
//     }
// ]